Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", owner: "vagrant", mount_options: ["dmode=777"]

  config.vm.provision "shell", inline: <<-SHELL
    echo "192.168.56.10  master-node" >> /etc/hosts
    echo "192.168.56.11  worker-node01" >> /etc/hosts
    echo "192.168.56.12  worker-node02" >> /etc/hosts
    echo "192.168.56.13  worker-node03" >> /etc/hosts
  SHELL

  config.vm.define "master-node" do |master|
    master.vm.box = "bento/ubuntu-20.04"
    master.vm.hostname = "master-node"
    master.vm.network "private_network", ip: "192.168.56.10"
    master.disksize.size = '10GB'
    master.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
        vb.name = "master-node"
    end
    master.vm.provision "shell", path: "scripts/nodes_all.sh"
    master.vm.provision "shell", path: "scripts/nodes_master.sh"
  end

  # Change here the number of nodes
  (1..3).each do |i|
    config.vm.define "worker-node0#{i}" do |node|
      node.vm.box = "bento/ubuntu-20.04"
      node.vm.hostname = "worker-node0#{i}"
      node.vm.network "private_network", ip: "192.168.56.1#{i}"
      node.disksize.size = '10GB'
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 2
        vb.name = "worker-node0#{i}"
      end
      node.vm.provision "shell", path: "scripts/nodes_all.sh"
      node.vm.provision "shell", path: "scripts/nodes_workers.sh"
    end
  end
end
